#!/bin/bash
#
# Example usage commands for FMC Hit Coun# Example 5: Large environment - both ALLOW and BLOCK rules
echo "Example 5: Large environment - both ALLOW and BLOCK rules"
echo "python3 fmc_rule_cleanup.py \\"
echo "  --host 192.168.1.100 \\"
echo "  --username apiuser \\"
echo "  --password 'YourPassword' \\"
echo "  --device 'firewall02.example.local' \\"
echo "  --rule-actions ALLOW BLOCK \\"
echo "  --year-threshold 2023 \\"
echo "  --max-rules 8000 \\"
echo "  --page-limit 1000 \\"
echo "  --timeout 30 \\"
echo "  --log-file extranet_analysis.log"
echo ""

echo "Remember to:"
echo "1. Always test with --dry-run first"
echo "2. Use appropriate --max-rules limits"
echo "3. Configure --exclude-zones for critical networks"
echo "4. Adjust --year-threshold based on your policy lifecycle"
echo "5. Choose appropriate --rule-actions (ALLOW, BLOCK, or both)"
echo "6. Enable logging for audit trails"
echo "FMC Hit Count Analysis - Example Usage"
echo "======================================"
echo ""

# Example 1: Basic dry run
echo "Example 1: Basic dry run"
echo "python3 fmc_rule_cleanup.py \\"
echo "  --host 192.168.1.100 \\"
echo "  --username apiuser \\"
echo "  --password 'YourPassword' \\"
echo "  --device 'firewall01.example.local' \\"
echo "  --dry-run"
echo ""

# Example 2: Production run with limits
echo "Example 2: Production run with safety limits"
echo "python3 fmc_rule_cleanup.py \\"
echo "  --host 192.168.1.100 \\"
echo "  --username apiuser \\"
echo "  --password 'YourPassword' \\"
echo "  --device 'firewall01.example.local' \\"
echo "  --max-rules 100 \\"
echo "  --log-file production_run.log"
echo ""

# Example 3: Debug mode with zone exclusions
echo "Example 3: Debug mode with zone exclusions"
echo "python3 fmc_rule_cleanup.py \\"
echo "  --host 192.168.1.100 \\"
echo "  --username apiuser \\"
echo "  --password 'YourPassword' \\"
echo "  --device 'firewall01.example.local' \\"
echo "  --exclude-zones TRUSTED DMZ CRITICAL \\"
echo "  --debug \\"
echo "  --dry-run"
echo ""

# Example 4: Target BLOCK rules from before 2022
echo "Example 4: Target BLOCK rules created before 2022"
echo "python3 fmc_rule_cleanup.py \\"
echo "  --host 192.168.1.100 \\"
echo "  --username apiuser \\"
echo "  --password 'YourPassword' \\"
echo "  --device 'firewall01.example.local' \\"
echo "  --year-threshold 2022 \\"
echo "  --rule-actions BLOCK \\"
echo "  --max-rules 100 \\"
echo "  --dry-run"
echo ""

# Example 5: Large environment configuration
echo "Example 5: Large environment - both ALLOW and BLOCK rules"
echo "python3 fmc_rule_cleanup.py \\"
echo "  --host 192.168.1.100 \\"
echo "  --username apiuser \\"
echo "  --password 'YourPassword' \\"
echo "  --device 'firewall02.example.local' \\"
echo "  --max-rules 8000 \\"
echo "  --page-limit 1000 \\"
echo "  --timeout 30 \\"
echo "  --log-file extranet_analysis.log"
echo ""

echo "Remember to:"
echo "1. Always test with --dry-run first"
echo "2. Use appropriate --max-rules limits"
echo "3. Configure --exclude-zones for critical networks"
echo "4. Enable logging for audit trails"